trigger:
- master
- release/*

phases:
- template: ../templates/blazor-build.yml
  parameters:
    queueName: DotNetCore-Windows
    variables:
      SignType: real
      TeamName: AspNetCore
    beforeBuild:
    - task: MicroBuildSigningPlugin@1
      displayName: 'Run compliance check'
      inputs:
        targetType: F
    - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@1
      displayName: Install CodeSigning plugin
      inputs:
        signType: $(SignType)
      condition: and(succeeded(), in(variables['SignType'], 'test', 'real'))

    afterBuild:
    - task: MicroBuildCleanup@1
      displayName: Perform Cleanup Tasks
      condition: succeededOrFailed()
